config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'tournaments#index'

  resources :tournaments, only: :show, id: Tournament::SLUG_PATTERN do
    member do
      get 'challenge'
      get 'leaderboard'
    end
  end
  resources :tournaments, only: :none do
    resources :brackets, path: 'brackets',
        tournament_id: Tournament::SLUG_PATTERN
  end

  namespace :admin do
    root to: 'tournaments#index'

    resources :tournaments, id: Tournament::SLUG_PATTERN
    resources :tournaments, only: :none do
      resources :teams, only: [:new, :create, :edit, :update],
        tournament_id: Tournament::SLUG_PATTERN
      resources :games, only: [:edit, :update],
        tournament_id: Tournament::SLUG_PATTERN
    end
  end

  match "/404" => "errors#404", via: [ :get, :post, :patch, :delete ]

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  SLUG_PATTERN = %r([a-z_\-\d]+-\d{4}(-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?)
  extend FriendlyId

  friendly_id :name_and_event, use: [:slugged]

  has_many :teams, dependent: :destroy
  has_many :games, dependent: :destroy
  has_many :brackets, dependent: :destroy

  scope :live, -> { where(live: true) }

  validates :name, presence: true
  validates :event, presence: true
  validates :start_date, presence: true

  validates :region0, presence: true
  validates :region1, presence: true
  validates :region2, presence: true
  validates :region3, presence: true

  # TODO: Switch to Postgres array type on switch to Rails 4
  # This is an array of hashes, with the shape:
  # {
  #   id: <bracket id>,
  #   position: <description of person>,
  #   headshot: <photo headshot id>
  # }
  serialize :featured, JSON

  after_initialize { self.featured ||= [] }

  def year
    start_date.year
  end

  def full_name
    "#{name} #{event} #{year}"
  end

  def started?
    DateTime.now > start_date
  end

  def normalize_friendly_id(s)
    "#{super}-#{year}"
  end

  def should_generate_new_friendly_id?
    name_changed? or event_changed? or start_date_changed? or super
  end

  def top_brackets(limit)
    brackets = self.brackets.includes(:user).order('score DESC').limit(limit)

    rank = 1
    ranks = brackets.each_with_index.map do |bracket, i|
      if i > 0 && bracket.score < brackets[i - 1].score
        rank = i + 1
      end
      rank
    end
    brackets.zip(ranks, fetch_champions(brackets))
  end

  def update_brackets!
    self.brackets
    .includes(tournament: { games: [:team1, :team2] })
    .find_each do |bracket|
      bracket.calculate_score
      bracket.save!
    end
  end

  private
  def name_and_event
    "#{name} #{event}"
  end

  def fetch_champions(brackets)
    ids = brackets.map { |bracket| bracket.picks[62] }.compact
    teams = Tournament::Team.where(id: ids)
    teams = teams.map { |team| [team.id, team] }
    teams = Hash[teams]
    brackets.map { |bracket| teams[bracket.picks[62]] }
  end
end

app/controllers/admin/tournaments_controller.rb
class Admin::TournamentsController < Admin::BaseController
  layout 'admin'

  def index
    @tournaments = Tournament.paginate(page: params[:page])
  end

  def show
    @tournament = Tournament.friendly.find(params[:id])
    @teams = @tournament.teams.order(:school)
    @games = @tournament.games.order(:position)
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      0.upto(62) do |position|
        @tournament.games.create!(position: position, start_time: @tournament.start_date).update_teams
      end
      redirect_to admin_tournaments_path
    else
      render 'new'
    end
  end

  def edit
    @tournament = Tournament.friendly.find(params[:id])
  end

  def update
    @tournament = Tournament.friendly.find(params[:id])

    if @tournament.update_attributes(tournament_params)
      redirect_to admin_tournaments_path
    else
      render 'edit'
    end
  end

  private
  def tournament_params
    params.require(:tournament).permit(
      :name,
      :event,
      :start_date,
      :region0,
      :region1,
      :region2,
      :region3,
      :live,
      :challenge_text
    )
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.live
  end

  def show
    @tournament = Tournament
      .includes(games: [:team1, :team2])
      .friendly.find(params[:id])

    if not @tournament.live? and current_user.try(:role) != 'admin'
      raise ActiveRecord::RecordNotFound
    end

    if user_signed_in?
      @bracket = @tournament.brackets.find_by_user_id(current_user)
    end
  end

  def challenge
    @tournament = Tournament.friendly.live.find(params[:id])
  end

  def leaderboard
    @tournament = Tournament.friendly.live.find(params[:id])
    @brackets = @tournament.top_brackets(2000)
    fetch_featured_brackets(@tournament)
    if user_signed_in?
      @user_bracket = @tournament.brackets.find_by_user_id(current_user.id)
      @display_user_bracket = @user_bracket &&
        !@brackets.map(&:first).include?(@user_bracket)
    end
  end

  private
  def fetch_featured_brackets(tournament)
    ids = tournament.featured.map { |info| info['id'] }
    brackets = tournament.brackets.includes(:user).where(id: ids)
    brackets = brackets.map do |bracket|
      [bracket.id, bracket]
    end
    brackets = Hash[brackets]
    tournament.featured.each do |info|
      info['bracket'] = brackets[info['id']]
      if info['bracket'].picks[62]
        info['champion'] = Team.find(info['bracket'].picks[62])
      end
    end
  end
end

app/helpers/admin/tournaments_helper.rb
module Admin::TournamentsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def tournament_json(tournament)
    tournament.to_json(tournament_json_options)
  end

  def tournament_bracket_json(bracket)
    bracket
      .as_json(tournament_bracket_json_options(bracket))
      .merge({
        editable: current_user == bracket.user
      })
      .to_json
  end

  def tournament_json_options
    {
      include: {
        games: {
          include: [:team1, :team2],
        }
      }
    }
  end

  def tournament_bracket_json_options(bracket)
    {
      include: { tournament: tournament_json_options },
    }
  end

  def bracket_freeze_time_in_words(tournament)
    time_ago = time_ago_in_words(tournament.start_date)
    if tournament.started?
      "Brackets froze #{time_ago} ago"
    else
      "Brackets freeze in #{time_ago}"
    end
  end
end

app/views/admin/tournaments/_form.html.slim
.row
  .col-xs-12
    = simple_form_for [:admin, tournament], defaults: { input_html: { class: 'form-control' } } do |f|
      legend= form_title
      = f.error_notification
      .form-inputs
        = f.input :name, hint: "eg. NCAA"
        = f.input :event, hint: "eg. Men's Basketball"
        = f.input :start_date, as: :datetime, input_html: {class: ''}, native: browser.chrome?
        = f.input :region0, label: "Top Left Region"
        = f.input :region1, label: "Bottom Left Region"
        = f.input :region2, label: "Top Right Region"
        = f.input :region3, label: "Bottom Right Region"
        = f.input :live, label: 'Currently Live', input_html: {class: ''}, wrapper: :inline_checkbox
        = f.input :challenge_text, cols: 5

      .form-actions
        = f.button :submit, class: 'btn btn-default'

app/views/admin/tournaments/edit.html.slim
- provide :title, "Editing #{@tournament.full_name}"

.row
  .col-xs-8
    = render 'admin/tournaments/form', form_title: "Edit #{@tournament.full_name}", tournament: @tournament

app/views/admin/tournaments/index.html.slim
- provide :title, 'Tournaments'
.row
  .col-xs-12
    h1 Tournaments
    = link_to 'Create Tournament', new_admin_tournament_path
    table.table
      thead
        th Name
        th
        th
        th Actions
      tbody
        - @tournaments.each do |tournament|
          tr
            td
              - if tournament.live?
                = link_to tournament.full_name, tournament
              - else
                = link_to "#{tournament.full_name} (Preview)", tournament
            - if tournament.live
              td.tournament-live= link_to 'Live', tournament
            - else
              td.tournament-not-live= link_to 'Not Live', [:edit, :admin, tournament]
            td
              = bracket_freeze_time_in_words(tournament)
              = " (#{tournament.start_date.strftime("%A at %l:%M %P")})"
            td.tournament-actions
              = link_to 'Manage Games', [:admin, tournament], class: 'btn btn-default btn-xs'
              = link_to 'Edit', [:edit, :admin, tournament], class: 'btn btn-default btn-xs'

app/views/admin/tournaments/new.html.slim
- provide :title, 'Create Tournament'

.row
  .col-xs-8
    = render 'admin/tournaments/form', form_title: "New Tournament", tournament: @tournament

app/views/admin/tournaments/show.html.slim
- provide :title, "Manage #{@tournament.full_name}"
.row
  .col-xs-12
    h1= @tournament.full_name

    h2 Statistics
    p
      strong Number of brackets: 
      = @tournament.brackets.count
      - if @tournament.live?
        = link_to '(Leaderboard)', leaderboard_tournament_path(@tournament)
    p= bracket_freeze_time_in_words(@tournament)
    ul.tournament-manage-actions
      - if @tournament.live?
        li
          = link_to 'Show Tournament', tournament_path(@tournament), class: 'btn btn-default btn-sm'
      - else
        li
          = link_to 'Preview Tournament', tournament_path(@tournament), class: 'btn btn-default btn-sm'
      li
        = link_to 'Edit Tournament', edit_admin_tournament_path(@tournament), class: 'btn btn-default btn-sm'

.row
  .col-xs-12.col-md-6
    h2 Games
    = render 'admin/partials/games_listing', games: @games
  .col-xs-12.col-md-6
    h2 Teams
    = link_to "Add team", new_admin_tournament_team_path(@tournament)
    ul
    - @teams.each do |team|
      li= link_to team.school, [:edit, :admin, @tournament, team]