config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'tournaments#index'

  resources :tournaments, only: :show, id: Tournament::SLUG_PATTERN do
    member do
      get 'challenge'
      get 'leaderboard'
    end
  end
  resources :tournaments, only: :none do
    resources :brackets, path: 'brackets',
        tournament_id: Tournament::SLUG_PATTERN
  end

  namespace :admin do
    root to: 'tournaments#index'

    resources :tournaments, id: Tournament::SLUG_PATTERN
    resources :tournaments, only: :none do
      resources :teams, only: [:new, :create, :edit, :update],
        tournament_id: Tournament::SLUG_PATTERN
      resources :games, only: [:edit, :update],
        tournament_id: Tournament::SLUG_PATTERN
    end
  end

  match "/404" => "errors#404", via: [ :get, :post, :patch, :delete ]

end

app/views/admin/partials/_flash.html.slim
- flash.each do |key, value|
  .alert(class="alert-#{key}")= value

app/views/admin/partials/_games_listing.html.slim
- round = 0
- games.each do |game|
  - if game.round != round
    br
    strong Round #{game.round}
    - round = game.round
  .game-listing-game
    = link_to game, edit_admin_tournament_game_path(game.tournament, game)

app/views/admin/partials/_header.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      a.navbar-brand(href=admin_root_path) Brackets Admin
    ul.nav.navbar-nav
      li
        = link_to 'Brackets Home', root_path